### ISSUE TITLE
Bot doesn't reply to any commands despite being online

### ISSUE THREAD

**Issue by abrahammurciano** [Epictek/tldr-Discord#3]
![Screenshot_20210702-003959.jpg](https://user-images.githubusercontent.com/25041135/124192514-51253880-dabd-11eb-8694-8074fee6c9ca.jpg)

**Comment by Epictek** [comment]
Fixed by https://github.com/Epictek/tldr-Discord/commit/28ab2142038a8ca9668f5feb223b29ab77de7751
